version: '2'

services: 
  dnfc:
    image: dnfc:latest
    ports:
      - "2000:2000"
      - "50010:50010"
    privileged: true
    container_name: devenv
    volumes: 
      - .:/home/develop/dnfc
